// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: analizadorFLex.flex


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class adalexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\25\u0100\1\u0200\11\u0100\1\u0300\17\u0100\1\u0400\247\u0100"+
    "\10\u0500\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\4\2\22\0\1\3\1\0\1\4\1\5"+
    "\2\0\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\11\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\0\1\27\1\30\1\31\2\30\1\32"+
    "\2\30\1\33\11\30\1\34\7\30\4\0\1\35\1\0"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\30\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\60\1\61\1\62\1\63\1\64"+
    "\1\65\1\30\1\0\1\66\10\0\1\2\32\0\1\1"+
    "\u01df\0\1\1\177\0\13\1\35\0\2\2\5\0\1\1"+
    "\57\0\1\1\240\0\1\1\377\0\u0100\67";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\4"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\2\17\1\20\1\21\1\22\1\1\1\23\31\24\1\25"+
    "\1\26\1\0\1\27\1\30\1\31\1\32\1\33\1\17"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\12\24\1\44\41\24\1\45\6\24\1\44\110\24\1\46"+
    "\25\24";

  private static int [] zzUnpackAction() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\70\0\70\0\160\0\70\0\70\0\70"+
    "\0\70\0\70\0\250\0\70\0\70\0\340\0\u0118\0\u0150"+
    "\0\u0188\0\u01c0\0\u01f8\0\70\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658"+
    "\0\u0690\0\u06c8\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0\0\u0818"+
    "\0\70\0\70\0\160\0\70\0\u0850\0\70\0\70\0\u0888"+
    "\0\u08c0\0\70\0\70\0\70\0\70\0\70\0\70\0\70"+
    "\0\70\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\u0ab8\0\u0af0\0\u0310\0\u0b28\0\u0b60\0\u0b98\0\u0bd0"+
    "\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u0d90"+
    "\0\u0dc8\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50"+
    "\0\u0f88\0\u0fc0\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110"+
    "\0\u1148\0\u1180\0\u11b8\0\u11f0\0\u1228\0\u0850\0\u1260\0\u1298"+
    "\0\u12d0\0\u1308\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458"+
    "\0\u1490\0\u14c8\0\u1500\0\u1538\0\u1570\0\u15a8\0\u15e0\0\u1618"+
    "\0\u1650\0\u1688\0\u16c0\0\u16f8\0\u1730\0\u1768\0\u17a0\0\u17d8"+
    "\0\u1810\0\u1848\0\u1880\0\u18b8\0\u18f0\0\u1928\0\u1960\0\u1998"+
    "\0\u19d0\0\u1a08\0\u1a40\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58"+
    "\0\u1b90\0\u1bc8\0\u1c00\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0\0\u1d18"+
    "\0\u1d50\0\u1d88\0\u1dc0\0\u1df8\0\u1e30\0\u1e68\0\u1ea0\0\u1ed8"+
    "\0\u1f10\0\u1f48\0\u1f80\0\u1fb8\0\u1ff0\0\u2028\0\u2060\0\u2098"+
    "\0\u20d0\0\u2108\0\u2140\0\u2178\0\u21b0\0\u21e8\0\u2220\0\u2258"+
    "\0\u2290\0\u22c8\0\u2300\0\u2338\0\u2370\0\u0310\0\u23a8\0\u23e0"+
    "\0\u2418\0\u2450\0\u2488\0\u24c0\0\u24f8\0\u2530\0\u2568\0\u25a0"+
    "\0\u25d8\0\u2610\0\u2648\0\u2680\0\u26b8\0\u26f0\0\u2728\0\u2760"+
    "\0\u2798\0\u27d0\0\u2808";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\2\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\31\1\45\1\31\1\46"+
    "\1\47\1\50\1\51\1\52\1\31\1\53\1\54\1\55"+
    "\1\56\1\31\1\57\1\60\1\31\1\61\1\3\74\0"+
    "\1\62\13\0\2\63\5\0\6\63\1\0\30\63\14\0"+
    "\1\64\72\0\1\65\70\0\1\66\76\0\1\67\60\0"+
    "\1\70\67\0\1\70\1\0\2\71\73\0\1\72\66\0"+
    "\1\73\1\74\1\75\66\0\1\76\1\77\66\0\1\100"+
    "\1\101\61\0\2\31\5\0\27\31\1\102\7\31\22\0"+
    "\2\31\5\0\37\31\22\0\2\31\5\0\16\31\1\103"+
    "\20\31\22\0\2\31\5\0\21\31\1\104\15\31\22\0"+
    "\2\31\5\0\23\31\1\105\13\31\22\0\2\31\5\0"+
    "\31\31\1\106\5\31\22\0\2\31\5\0\10\31\1\107"+
    "\1\110\7\31\1\111\1\31\1\112\3\31\1\113\1\31"+
    "\1\114\5\31\22\0\2\31\5\0\13\31\1\115\10\31"+
    "\1\116\12\31\22\0\2\31\5\0\7\31\1\117\14\31"+
    "\1\120\12\31\22\0\2\31\5\0\13\31\1\121\3\31"+
    "\1\122\4\31\1\114\12\31\22\0\2\31\5\0\21\31"+
    "\1\123\1\31\1\124\11\31\1\125\1\31\22\0\2\31"+
    "\5\0\24\31\1\126\5\31\1\127\4\31\22\0\2\31"+
    "\5\0\13\31\1\130\10\31\1\131\12\31\22\0\2\31"+
    "\5\0\14\31\1\114\6\31\1\114\4\31\1\114\6\31"+
    "\22\0\2\31\5\0\17\31\1\132\4\31\1\133\12\31"+
    "\22\0\2\31\5\0\24\31\1\112\12\31\22\0\2\31"+
    "\5\0\13\31\1\134\10\31\1\135\5\31\1\136\4\31"+
    "\22\0\2\31\5\0\14\31\1\114\12\31\1\114\1\31"+
    "\1\137\1\135\4\31\22\0\2\31\5\0\7\31\1\140"+
    "\17\31\1\141\7\31\22\0\2\31\5\0\7\31\1\142"+
    "\3\31\1\143\23\31\22\0\2\31\5\0\13\31\1\144"+
    "\16\31\1\145\4\31\22\0\2\31\5\0\7\31\1\146"+
    "\3\31\1\147\2\31\1\150\17\31\1\151\22\0\2\31"+
    "\5\0\23\31\1\152\4\31\1\153\6\31\22\0\2\31"+
    "\5\0\16\31\1\154\1\155\17\31\22\0\2\31\5\0"+
    "\24\31\1\126\12\31\3\0\3\156\14\0\2\156\5\0"+
    "\37\156\22\0\2\70\66\0\2\71\66\0\2\31\5\0"+
    "\27\31\1\157\7\31\22\0\2\31\5\0\7\31\1\160"+
    "\27\31\22\0\2\31\5\0\24\31\1\161\12\31\22\0"+
    "\2\31\5\0\31\31\1\162\5\31\22\0\2\31\5\0"+
    "\27\31\1\163\7\31\22\0\2\31\5\0\24\31\1\164"+
    "\3\31\1\165\6\31\22\0\2\31\5\0\11\31\1\166"+
    "\25\31\22\0\2\31\5\0\17\31\1\167\1\31\1\114"+
    "\15\31\22\0\2\31\5\0\12\31\1\114\24\31\22\0"+
    "\2\31\5\0\27\31\1\170\7\31\22\0\2\31\5\0"+
    "\15\31\1\171\21\31\22\0\2\31\5\0\12\31\1\172"+
    "\24\31\22\0\2\31\5\0\30\31\1\153\6\31\22\0"+
    "\2\31\5\0\23\31\1\173\13\31\22\0\2\31\5\0"+
    "\11\31\1\174\7\31\1\175\15\31\22\0\2\31\5\0"+
    "\15\31\1\176\21\31\22\0\2\31\5\0\30\31\1\177"+
    "\6\31\22\0\2\31\5\0\12\31\1\114\16\31\1\200"+
    "\5\31\22\0\2\31\5\0\11\31\1\201\5\31\1\135"+
    "\17\31\22\0\2\31\5\0\27\31\1\114\7\31\22\0"+
    "\2\31\5\0\23\31\1\202\13\31\22\0\2\31\5\0"+
    "\23\31\1\203\13\31\22\0\2\31\5\0\31\31\1\204"+
    "\5\31\22\0\2\31\5\0\22\31\1\205\14\31\22\0"+
    "\2\31\5\0\24\31\1\206\12\31\22\0\2\31\5\0"+
    "\34\31\1\114\2\31\22\0\2\31\5\0\31\31\1\114"+
    "\5\31\22\0\2\31\5\0\21\31\1\207\15\31\22\0"+
    "\2\31\5\0\16\31\1\210\20\31\22\0\2\31\5\0"+
    "\11\31\1\211\25\31\22\0\2\31\5\0\7\31\1\212"+
    "\7\31\1\213\4\31\1\214\12\31\22\0\2\31\5\0"+
    "\17\31\1\117\3\31\1\215\13\31\22\0\2\31\5\0"+
    "\11\31\1\216\10\31\1\114\1\217\2\31\1\220\2\31"+
    "\1\221\1\31\1\222\3\31\22\0\2\31\5\0\21\31"+
    "\1\223\3\31\1\224\11\31\22\0\2\31\5\0\10\31"+
    "\1\225\26\31\22\0\2\31\5\0\15\31\1\226\12\31"+
    "\1\227\6\31\22\0\2\31\5\0\27\31\1\230\7\31"+
    "\22\0\2\31\5\0\13\31\1\231\23\31\22\0\2\31"+
    "\5\0\25\31\1\153\11\31\22\0\2\31\5\0\31\31"+
    "\1\232\5\31\22\0\2\31\5\0\13\31\1\114\23\31"+
    "\22\0\2\31\5\0\13\31\1\231\3\31\1\233\17\31"+
    "\22\0\2\31\5\0\31\31\1\234\5\31\22\0\2\31"+
    "\5\0\7\31\1\235\27\31\22\0\2\31\5\0\27\31"+
    "\1\236\7\31\22\0\2\31\5\0\7\31\1\237\27\31"+
    "\22\0\2\31\5\0\13\31\1\240\23\31\22\0\2\31"+
    "\5\0\17\31\1\241\17\31\22\0\2\31\5\0\27\31"+
    "\1\135\7\31\22\0\2\31\5\0\31\31\1\242\5\31"+
    "\22\0\2\31\5\0\13\31\1\243\23\31\22\0\2\31"+
    "\5\0\7\31\1\244\27\31\22\0\2\31\5\0\7\31"+
    "\1\172\27\31\22\0\2\31\5\0\17\31\1\231\17\31"+
    "\22\0\2\31\5\0\36\31\1\114\22\0\2\31\5\0"+
    "\30\31\1\245\6\31\22\0\2\31\5\0\21\31\1\246"+
    "\15\31\22\0\2\31\5\0\7\31\1\172\21\31\1\247"+
    "\5\31\22\0\2\31\5\0\17\31\1\250\17\31\22\0"+
    "\2\31\5\0\13\31\1\114\3\31\1\251\17\31\22\0"+
    "\2\31\5\0\27\31\1\172\7\31\22\0\2\31\5\0"+
    "\13\31\1\252\23\31\22\0\2\31\5\0\11\31\1\253"+
    "\25\31\22\0\2\31\5\0\13\31\1\254\23\31\22\0"+
    "\2\31\5\0\24\31\1\114\12\31\22\0\2\31\5\0"+
    "\17\31\1\255\17\31\22\0\2\31\5\0\25\31\1\114"+
    "\11\31\22\0\2\31\5\0\21\31\1\114\15\31\22\0"+
    "\2\31\5\0\13\31\1\256\23\31\22\0\2\31\5\0"+
    "\20\31\1\257\16\31\22\0\2\31\5\0\15\31\1\260"+
    "\21\31\22\0\2\31\5\0\33\31\1\261\3\31\22\0"+
    "\2\31\5\0\11\31\1\262\17\31\1\263\5\31\22\0"+
    "\2\31\5\0\15\31\1\153\21\31\22\0\2\31\5\0"+
    "\24\31\1\264\12\31\22\0\2\31\5\0\7\31\1\265"+
    "\27\31\22\0\2\31\5\0\32\31\1\266\4\31\22\0"+
    "\2\31\5\0\32\31\1\267\4\31\22\0\2\31\5\0"+
    "\13\31\1\270\23\31\22\0\2\31\5\0\13\31\1\271"+
    "\23\31\22\0\2\31\5\0\7\31\1\272\27\31\22\0"+
    "\2\31\5\0\31\31\1\273\5\31\22\0\2\31\5\0"+
    "\15\31\1\274\21\31\22\0\2\31\5\0\20\31\1\114"+
    "\16\31\22\0\2\31\5\0\22\31\1\275\14\31\22\0"+
    "\2\31\5\0\23\31\1\114\13\31\22\0\2\31\5\0"+
    "\17\31\1\207\17\31\22\0\2\31\5\0\21\31\1\153"+
    "\15\31\22\0\2\31\5\0\16\31\1\114\20\31\22\0"+
    "\2\31\5\0\36\31\1\276\22\0\2\31\5\0\7\31"+
    "\1\277\27\31\22\0\2\31\5\0\31\31\1\276\5\31"+
    "\22\0\2\31\5\0\15\31\1\300\21\31\22\0\2\31"+
    "\5\0\23\31\1\301\13\31\22\0\2\31\5\0\27\31"+
    "\1\302\7\31\22\0\2\31\5\0\25\31\1\135\2\31"+
    "\1\303\6\31\22\0\2\31\5\0\30\31\1\274\6\31"+
    "\22\0\2\31\5\0\31\31\1\304\5\31\22\0\2\31"+
    "\5\0\7\31\1\305\27\31\22\0\2\31\5\0\7\31"+
    "\1\114\27\31\22\0\2\31\5\0\31\31\1\303\5\31"+
    "\22\0\2\31\5\0\14\31\1\114\22\31\22\0\2\31"+
    "\5\0\25\31\1\253\11\31\22\0\2\31\5\0\31\31"+
    "\1\306\5\31\22\0\2\31\5\0\27\31\1\307\7\31"+
    "\22\0\2\31\5\0\31\31\1\274\5\31\22\0\2\31"+
    "\5\0\27\31\1\303\7\31\22\0\2\31\5\0\7\31"+
    "\1\215\27\31\22\0\2\31\5\0\22\31\1\247\14\31"+
    "\22\0\2\31\5\0\7\31\1\310\27\31\22\0\2\31"+
    "\5\0\13\31\1\311\23\31\22\0\2\31\5\0\13\31"+
    "\1\312\23\31\22\0\2\31\5\0\27\31\1\112\7\31"+
    "\22\0\2\31\5\0\22\31\1\313\14\31\22\0\2\31"+
    "\5\0\13\31\1\314\23\31\22\0\2\31\5\0\27\31"+
    "\1\231\7\31\22\0\2\31\5\0\27\31\1\117\7\31"+
    "\22\0\2\31\5\0\11\31\1\135\25\31\22\0\2\31"+
    "\5\0\27\31\1\261\7\31\22\0\2\31\5\0\36\31"+
    "\1\151\22\0\2\31\5\0\13\31\1\112\23\31\22\0"+
    "\2\31\5\0\17\31\1\315\17\31\22\0\2\31\5\0"+
    "\11\31\1\316\25\31\22\0\2\31\5\0\13\31\1\317"+
    "\23\31\22\0\2\31\5\0\15\31\1\276\21\31\22\0"+
    "\2\31\5\0\7\31\1\271\27\31\22\0\2\31\5\0"+
    "\30\31\1\114\6\31\22\0\2\31\5\0\7\31\1\320"+
    "\27\31\22\0\2\31\5\0\27\31\1\153\7\31\22\0"+
    "\2\31\5\0\17\31\1\321\17\31\22\0\2\31\5\0"+
    "\17\31\1\322\17\31\22\0\2\31\5\0\31\31\1\153"+
    "\5\31\22\0\2\31\5\0\12\31\1\323\24\31\22\0"+
    "\2\31\5\0\11\31\1\255\25\31\22\0\2\31\5\0"+
    "\13\31\1\303\23\31\22\0\2\31\5\0\32\31\1\153"+
    "\4\31\22\0\2\31\5\0\23\31\1\261\13\31\22\0"+
    "\2\31\5\0\31\31\1\300\5\31\22\0\2\31\5\0"+
    "\27\31\1\276\7\31\22\0\2\31\5\0\23\31\1\135"+
    "\13\31\22\0\2\31\5\0\24\31\1\231\12\31\22\0"+
    "\2\31\5\0\11\31\1\114\25\31\22\0\2\31\5\0"+
    "\32\31\1\305\4\31\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10304];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\11\1\1\5\11\1\1\2\11\6\1\1\11"+
    "\34\1\2\11\1\0\1\11\1\1\2\11\2\1\10\11"+
    "\222\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[211];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  adalexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println(yytext() + "\t\t ERROR");
            }
            // fall through
          case 39: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 40: break;
          case 3:
            { 
            }
            // fall through
          case 41: break;
          case 4:
            { System.out.println(yytext() + "\t\t apostrofe");
            }
            // fall through
          case 42: break;
          case 5:
            { System.out.println(yytext() + "\t\t NUMERO SIGN");
            }
            // fall through
          case 43: break;
          case 6:
            { System.out.println(yytext() + "\t\t AMPERSAND");
            }
            // fall through
          case 44: break;
          case 7:
            { System.out.println(yytext() + "\t\t LEFT PARENTHESIS");
            }
            // fall through
          case 45: break;
          case 8:
            { System.out.println(yytext() + "\t\t RIGHT PARENTHESIS");
            }
            // fall through
          case 46: break;
          case 9:
            { System.out.println(yytext() +"\t\t OPERADOR DE MULTIPLICACION");
            }
            // fall through
          case 47: break;
          case 10:
            { System.out.println(yytext() +"\t\t OPERADOR DE SUMA");
            }
            // fall through
          case 48: break;
          case 11:
            { System.out.println(yytext() + "\t\t coma");
            }
            // fall through
          case 49: break;
          case 12:
            { System.out.println(yytext() +"\t\t OPERADOR DE RESTA");
            }
            // fall through
          case 50: break;
          case 13:
            { System.out.println(yytext() + "\t\t punto");
            }
            // fall through
          case 51: break;
          case 14:
            { System.out.println(yytext() +"\t\t OPERADOR DE DIVISION");
            }
            // fall through
          case 52: break;
          case 15:
            { System.out.println(yytext() +"\t\t ENTERO");
            }
            // fall through
          case 53: break;
          case 16:
            { System.out.println(yytext() +"\t\t dos_puntos");
            }
            // fall through
          case 54: break;
          case 17:
            { System.out.println(yytext() + "\t\t punto_coma");
            }
            // fall through
          case 55: break;
          case 18:
            { System.out.println(yytext() +"\t\t OPERADOR MENOR QUE ");
            }
            // fall through
          case 56: break;
          case 19:
            { System.out.println(yytext() +"\t\t OPERADOR MAYOR QUE ");
            }
            // fall through
          case 57: break;
          case 20:
            { System.out.println(yytext() +"\t\t IDENTIFICADOR");
            }
            // fall through
          case 58: break;
          case 21:
            { System.out.println(yytext() +"\t\t OPERADOR BOOLEANO ");
            }
            // fall through
          case 59: break;
          case 22:
            { System.out.println(yytext() +"\t\t STRING");
            }
            // fall through
          case 60: break;
          case 23:
            { System.out.println(yytext() + "\t\t DOUBLE STAR");
            }
            // fall through
          case 61: break;
          case 24:
            { System.out.println(yytext() + "\t\t guion");
            }
            // fall through
          case 62: break;
          case 25:
            { System.out.println(yytext() + "\t\t DOUBLE DOT");
            }
            // fall through
          case 63: break;
          case 26:
            { System.out.println(yytext() +"\t\t OPERADOR DEVISOR O ESCALABILIDAD ");
            }
            // fall through
          case 64: break;
          case 27:
            { System.out.println(yytext() +"\t\t DECIMAL");
            }
            // fall through
          case 65: break;
          case 28:
            { System.out.println(yytext() +"\t\t ASIGNACION");
            }
            // fall through
          case 66: break;
          case 29:
            { System.out.println(yytext() + "\t\t LEFT LABEL");
            }
            // fall through
          case 67: break;
          case 30:
            { System.out.println(yytext() +"\t\t OPERADOR MENOR O IGUAL ");
            }
            // fall through
          case 68: break;
          case 31:
            { System.out.println(yytext() + "\t\t BOX");
            }
            // fall through
          case 69: break;
          case 32:
            { System.out.println(yytext() +"\t\t OPERADOR DE IGUALDAD ");
            }
            // fall through
          case 70: break;
          case 33:
            { System.out.println(yytext() + "\t\t flecha");
            }
            // fall through
          case 71: break;
          case 34:
            { System.out.println(yytext() +"\t\t OPERADOR MAYOR O IGUAL ");
            }
            // fall through
          case 72: break;
          case 35:
            { System.out.println(yytext() + "\t\t RIGHT LABEL");
            }
            // fall through
          case 73: break;
          case 36:
            { System.out.println(yytext() +"\t\t PALABRA_RESERVADA WORD");
            }
            // fall through
          case 74: break;
          case 37:
            { System.out.println(yytext() + "\t\t COMENTARIO");
            }
            // fall through
          case 75: break;
          case 38:
            { System.out.println(yytext() + "\t\t DATA TYPE");
            }
            // fall through
          case 76: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java adalexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        adalexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new adalexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
